-- No-op migration (placeholder for journal idx 10).
--
-- History: idx 10 existed in drizzle/meta/_journal.json but its .sql file was
-- never committed, which made `drizzle-kit migrate` fail to load the journal
-- and silently skip every later migration (including 0011_add_user_photo) on
-- production. The fix is to keep a valid .sql file at this index.
--
-- It MUST contain at least one statement: `drizzle-kit generate` prunes
-- migration files that have no statements, which would re-introduce the
-- original bug. The statement below is an intentional no-op (it changes
-- nothing) and is safe to re-run on any database.
--
-- Migrations are applied by timestamp ordering, so editing this file does not
-- cause it to re-run on databases that have already advanced past idx 10.
SELECT 1;
