/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    posts: Post;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    faqs: Faq;
    'team-members': TeamMember;
    media: Media;
    logos: Logo;
    partners: Partner;
    events: Event;
    resources: Resource;
    services: Service;
    strategists: Strategist;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    strategists: StrategistsSelect<false> | StrategistsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'announcement-bar': AnnouncementBar;
    'signup-page-content': SignupPageContent;
    'partners-page': PartnersPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'announcement-bar': AnnouncementBarSelect<false> | AnnouncementBarSelect<true>;
    'signup-page-content': SignupPageContentSelect<false> | SignupPageContentSelect<true>;
    'partners-page': PartnersPageSelect<false> | PartnersPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment. Use "home" for the homepage.
   */
  slug: string;
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            backgroundImage?: (number | null) | Media;
            variant?: ('centered' | 'left-aligned' | 'split') | null;
            /**
             * Badge text above the heading, e.g. "A Social Traders Verified Enterprise"
             */
            eyebrow?: string | null;
            /**
             * Handscript tagline below heading, e.g. "Grow local. Grow together."
             */
            handnote?: string | null;
            /**
             * Info chips displayed below the CTA buttons
             */
            chips?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            /**
             * Show monthly/annual billing toggle.
             */
            showToggle?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            heading?: string | null;
            testimonials?: (number | Testimonial)[] | null;
            layout?: ('grid' | 'carousel') | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            faqs?: (number | Faq)[] | null;
            /**
             * Filter FAQs by category, or show all.
             */
            category?: ('all' | 'general' | 'billing' | 'features' | 'technical') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            logos?: (number | Logo)[] | null;
            autoScroll?: boolean | null;
            /**
             * Text-only items (no image) — e.g. partner or funder names
             */
            textItems?:
              | {
                  name: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logo-strip';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            features?:
              | {
                  /**
                   * Icon name or SVG path.
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'feature-grid';
          }
        | {
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content-with-image';
          }
        | {
            heading?: string | null;
            /**
             * YouTube or Vimeo URL.
             */
            url: string;
            poster?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video-embed';
          }
        | {
            heading: string;
            subheading?: string | null;
            ctaLabel: string;
            ctaHref: string;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            variant?: ('teal' | 'plum' | 'lime') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-banner';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            members?: (number | TeamMember)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team-section';
          }
        | {
            heading?: string | null;
            stats?:
              | {
                  /**
                   * e.g. "500+" or "3×".
                   */
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats-banner';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            maxWidth?: ('narrow' | 'normal' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            heading?: string | null;
            steps: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            /**
             * Photo shown on the right side of the section
             */
            sectionImage?: (number | null) | Media;
            /**
             * Badge text overlaid on the image, e.g. "Live events + webinars"
             */
            imageBadge?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'how-it-works';
          }
        | {
            sectionLabel?: string | null;
            heading: string;
            /**
             * Italic text appended to the heading (rendered in <em>)
             */
            subheading?: string | null;
            /**
             * Body paragraphs shown in the left column
             */
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Blockquote highlighted below the body paragraphs
             */
            pullQuote?: string | null;
            /**
             * Stat cards shown in the right column
             */
            stats?:
              | {
                  /**
                   * e.g. "400+" or "$400K"
                   */
                  value: string;
                  description: string;
                  tone?: ('teal' | 'lime' | 'plain') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            quote: string;
            /**
             * Who said this, e.g. "A Local Canberra Business Owner"
             */
            attribution?: string | null;
            /**
             * Trust badges displayed below the quote
             */
            badges?:
              | {
                  label: string;
                  icon?: ('verified' | 'ndis' | 'location') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'big-quote';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            /**
             * Each tab is a community pillar (events, webinar, community, support, etc.)
             */
            tabs: {
              /**
               * Tab button label, e.g. "In-Person Events"
               */
              label: string;
              /**
               * Anchor/key for this tab, e.g. "events"
               */
              slug: string;
              /**
               * Access badge text, e.g. "Subscribers Only"
               */
              badge?: string | null;
              /**
               * Show a lock icon on the badge
               */
              locked?: boolean | null;
              /**
               * Small tag shown at top of panel, e.g. "Live · Every Week"
               */
              tagLine?: string | null;
              panelHeading?: string | null;
              panelDescription?: string | null;
              /**
               * Bullet points in the right column of the panel
               */
              features?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'community';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  role?: string | null;
  company?: string | null;
  avatar?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('general' | 'billing' | 'features' | 'technical') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  name: string;
  image: number | Media;
  /**
   * Optional link when the logo is clicked.
   */
  url?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  publishedAt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  client: string;
  /**
   * One-line result summary, e.g. "3× organic traffic in 6 months".
   */
  outcome?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * URL slug for /partners/{slug} deep page. Auto-generated from name on save if left blank.
   */
  slug?: string | null;
  /**
   * Used for directory filter chips and grouping
   */
  category:
    | 'technology'
    | 'creative-media'
    | 'community-delivery'
    | 'industry-government'
    | 'accelerator-capital'
    | 'research-education';
  /**
   * Abstract mono glyph used as a placeholder partner mark. Leave blank to use a sensible default by category.
   */
  shape?: ('circle' | 'diamond' | 'triangle' | 'leaf' | 'hex' | 'arc' | 'bars' | 'cross') | null;
  /**
   * Short description shown in the directory card
   */
  description?: string | null;
  /**
   * e.g. "Canberra", "ACT", "Sydney", "ACT · Global"
   */
  region?: string | null;
  /**
   * Year the partnership began, e.g. "2023" or "2024"
   */
  since?: string | null;
  /**
   * What this partner brings — e.g. "Reviews automation · AI customer messaging · listing management". Rendered under "What they bring" on the directory card.
   */
  contribution?: string | null;
  /**
   * How we collaborate — e.g. "Bundled into client subscriptions; we configure and support locally." Rendered under "How we work together".
   */
  howWeWork?: string | null;
  /**
   * Full URL including https://
   */
  website?: string | null;
  /**
   * Primary contact person (optional)
   */
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * Optional logo image (square or landscape, min 200px wide)
   */
  logo?: (number | null) | Media;
  /**
   * Show in the Featured Partners wall at the top of the /partners page
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL slug. Auto-generated from title on save if left blank.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Date the event runs on. Past dates remain visible as recordings.
   */
  date: string;
  /**
   * Display time, e.g. "12:30 – 1:30 pm" or "10:00 – 11:30 am".
   */
  time?: string | null;
  type?: ('webinar' | 'workshop' | 'community') | null;
  /**
   * For in-person events. Leave blank for online.
   */
  location?: string | null;
  /**
   * Free-text seat availability shown to members, e.g. "8 of 12 spots left" or "Open registration".
   */
  seats?: string | null;
  /**
   * External registration URL (e.g. Eventbrite, Zoom).
   */
  registerUrl?: string | null;
  /**
   * For past events — surfaces in the recordings grid once uploaded.
   */
  recording?: (number | null) | Media;
  /**
   * Pin to the hero slot at the top of the public /events hub. Only the first featured upcoming event is shown.
   */
  featured?: boolean | null;
  /**
   * Public categorisation used by the /events hub filter chips. Independent of the internal `type` field (which still drives the dashboard labels).
   */
  category?: ('summit' | 'workshop' | 'mixer' | 'clinic' | 'community' | 'webinar') | null;
  /**
   * Display tag on the public hub (e.g. "Annual Summit", "Workshop", "Mixer"). Falls back to the category label when blank.
   */
  tag?: string | null;
  /**
   * Who the event is for, shown on the public detail page.
   */
  audience?: string | null;
  /**
   * Free-text cost line — e.g. "Free", "Free · RSVP", "Free for members · $40 guests".
   */
  cost?: string | null;
  /**
   * Override for non-standard date strings — e.g. "Date to be confirmed", "Fortnightly · alternating Tuesdays". When blank, `date` is auto-formatted.
   */
  dateDisplay?: string | null;
  /**
   * Set true if a hand-built landing page exists at /events/{slug}. The generic detail route will 307 to it.
   */
  bespoke?: boolean | null;
  /**
   * Primary venue/co-host for this event (e.g. Canberra Innovation Network). Renders the partner lock-up on the event detail page and surfaces this event on the partner page.
   */
  host?: (number | null) | Partner;
  /**
   * Other partners co-promoting this event. Surfaces this event on each partner page so they have a single URL to share with their audience.
   */
  partners?: (number | Partner)[] | null;
  /**
   * Optional. When set, signed-in members can RSVP normally but the public mailto CTA is hidden and replaced with a "Members get early access" banner until this date passes. Drives paid-tier urgency for high-demand events. Leave blank for open-RSVP-from-launch.
   */
  memberPreviewUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  tag: 'Guide' | 'Template' | 'Course' | 'Video' | 'Webinar';
  /**
   * Card thumbnail colour. Try to spread tones across the grid for visual rhythm.
   */
  tone?: ('cream' | 'lime' | 'teal' | 'plum' | 'lav') | null;
  /**
   * Short meta line, e.g. "5-min read" or "PDF · Editable" or "Self-paced · 2 hrs".
   */
  meta?: string | null;
  /**
   * Optional cover image. Falls back to a solid-colour thumbnail using `tone`.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Where the card links to — a hosted PDF, external course, YouTube, etc.
   */
  url?: string | null;
  /**
   * Uncheck to gate behind a paid plan.
   */
  free?: boolean | null;
  publishedAt?: string | null;
  /**
   * Show in the dashboard "Suggested first reads" card. Aim for 3 featured at any time.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Consultancy + done-with-you services. Use sortOrder to control card order; lower numbers first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Used for the /services/[slug] URL. Keep it kebab-case (e.g. "growth-call", "website-setup").
   */
  slug: string;
  /**
   * Two or three sentences. Renders below the title on the card.
   */
  description: string;
  category?: ('strategy' | 'build' | 'marketing' | 'ops') | null;
  /**
   * Icon background colour on the card.
   */
  tone?: ('lime' | 'teal' | 'plum' | 'lav') | null;
  icon?: ('cal' | 'globe' | 'megaphone' | 'type' | 'trend' | 'share' | 'briefcase') | null;
  /**
   * Display price, e.g. "A$390 / mo" or "From A$1,950" or "Complimentary". Leave blank if pricing is bespoke.
   */
  price?: string | null;
  /**
   * Tiny label under the price, e.g. "first call free", "fixed project fee", "month-to-month".
   */
  priceLabel?: string | null;
  /**
   * Card button text. "Book a time" for the Growth Call, "Request" otherwise.
   */
  ctaLabel?: string | null;
  /**
   * Uncheck to hide from /services without deleting the row.
   */
  active?: boolean | null;
  /**
   * Lower numbers appear first. Growth Call is usually 0.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strategists".
 */
export interface Strategist {
  id: number;
  name: string;
  /**
   * Stable assignment key stored on user_profiles.assigned_strategist_id. Auto-generated from name on save if left blank.
   */
  slug?: string | null;
  /**
   * e.g. "Growth Strategist", "Senior Strategist"
   */
  role: string;
  photo?: (number | null) | Media;
  email: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Full URL including https://
   */
  calendlyUrl?: string | null;
  /**
   * Only active strategists receive auto-assignment of new signups. Inactive strategists keep existing assignments.
   */
  active?: boolean | null;
  /**
   * Lower numbers appear first in admin lists
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'strategists';
        value: number | Strategist;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctaLabel?: T;
              ctaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              backgroundImage?: T;
              variant?: T;
              eyebrow?: T;
              handnote?: T;
              chips?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              heading?: T;
              subheading?: T;
              showToggle?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              testimonials?: T;
              layout?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              faqs?: T;
              category?: T;
              id?: T;
              blockName?: T;
            };
        'logo-strip'?:
          | T
          | {
              heading?: T;
              logos?: T;
              autoScroll?: T;
              textItems?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'feature-grid'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        'content-with-image'?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              imagePosition?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        'video-embed'?:
          | T
          | {
              heading?: T;
              url?: T;
              poster?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        'cta-banner'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctaLabel?: T;
              ctaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        'team-section'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              members?: T;
              id?: T;
              blockName?: T;
            };
        'stats-banner'?:
          | T
          | {
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
        'how-it-works'?:
          | T
          | {
              heading?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              sectionImage?: T;
              imageBadge?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              sectionLabel?: T;
              heading?: T;
              subheading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              pullQuote?: T;
              stats?:
                | T
                | {
                    value?: T;
                    description?: T;
                    tone?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'big-quote'?:
          | T
          | {
              quote?: T;
              attribution?: T;
              badges?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        community?:
          | T
          | {
              heading?: T;
              subheading?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    slug?: T;
                    badge?: T;
                    locked?: T;
                    tagLine?: T;
                    panelHeading?: T;
                    panelDescription?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  content?: T;
  excerpt?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  outcome?: T;
  body?: T;
  image?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  avatar?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  shape?: T;
  description?: T;
  region?: T;
  since?: T;
  contribution?: T;
  howWeWork?: T;
  website?: T;
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  logo?: T;
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  date?: T;
  time?: T;
  type?: T;
  location?: T;
  seats?: T;
  registerUrl?: T;
  recording?: T;
  featured?: T;
  category?: T;
  tag?: T;
  audience?: T;
  cost?: T;
  dateDisplay?: T;
  bespoke?: T;
  host?: T;
  partners?: T;
  memberPreviewUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  tone?: T;
  meta?: T;
  thumbnail?: T;
  url?: T;
  free?: T;
  publishedAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  tone?: T;
  icon?: T;
  price?: T;
  priceLabel?: T;
  ctaLabel?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strategists_select".
 */
export interface StrategistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  photo?: T;
  email?: T;
  bio?: T;
  calendlyUrl?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  supportEmail?: string | null;
  /**
   * Display phone number, e.g. "02 5119 0005"
   */
  phone?: string | null;
  /**
   * Display address, e.g. "Level 4, 1 Moore St, Canberra ACT 2601"
   */
  address?: string | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  navItems?:
    | {
        label: string;
        href: string;
        isExternal?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-bar".
 */
export interface AnnouncementBar {
  id: number;
  enabled?: boolean | null;
  message?: string | null;
  linkText?: string | null;
  linkHref?: string | null;
  /**
   * Hex colour code, e.g. #0D3F48.
   */
  bgColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signup-page-content".
 */
export interface SignupPageContent {
  id: number;
  foundations?: {
    /**
     * Main heading for the Foundations signup page
     */
    title?: string | null;
    /**
     * Subheading below the title
     */
    tagline?: string | null;
    /**
     * Feature list shown on the signup page
     */
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional add-on upsell line (e.g. "Add Search AI from $99/mo")
     */
    addon?: string | null;
    /**
     * Trust badges / guarantees shown below the feature list
     */
    trustItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  growth?: {
    /**
     * Main heading for the Growth signup page
     */
    title?: string | null;
    /**
     * Subheading below the title
     */
    tagline?: string | null;
    /**
     * Feature list shown on the signup page
     */
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional add-on upsell line (e.g. "Add Search AI from $99/mo")
     */
    addon?: string | null;
    /**
     * Trust badges / guarantees shown below the feature list
     */
    trustItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  accelerate?: {
    /**
     * Main heading for the Accelerate signup page
     */
    title?: string | null;
    /**
     * Subheading below the title
     */
    tagline?: string | null;
    /**
     * Feature list shown on the signup page
     */
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional add-on upsell line (e.g. "Add Search AI from $99/mo")
     */
    addon?: string | null;
    /**
     * Trust badges / guarantees shown below the feature list
     */
    trustItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-page".
 */
export interface PartnersPage {
  id: number;
  heroEyebrow?: string | null;
  heroHeading?: string | null;
  /**
   * Paragraph below the heading
   */
  heroSubheading?: string | null;
  heroCtaLabel?: string | null;
  heroCtaHref?: string | null;
  heroSecondaryCtaLabel?: string | null;
  heroSecondaryCtaHref?: string | null;
  heroChips?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  featuredWallHeading?: string | null;
  /**
   * Short lead text shown beside the heading
   */
  featuredWallLead?: string | null;
  directoryHeading?: string | null;
  directoryLead?: string | null;
  benefitsHeading?: string | null;
  benefitsLead?: string | null;
  /**
   * Up to 3 benefit cards
   */
  benefits?:
    | {
        /**
         * Small label e.g. "01 — Reach"
         */
        tag: string;
        heading: string;
        body: string;
        /**
         * Handscript pull-quote (optional)
         */
        handnote?: string | null;
        id?: string | null;
      }[]
    | null;
  proofHeading?: string | null;
  proofLead?: string | null;
  /**
   * Up to 3 stat cards
   */
  proofStats?:
    | {
        /**
         * Small label e.g. "Community"
         */
        tag?: string | null;
        /**
         * The large number e.g. "400+"
         */
        num: string;
        /**
         * Script unit e.g. "members"
         */
        unit?: string | null;
        heading: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Up to 2 pull quotes
   */
  proofQuotes?:
    | {
        text: string;
        attribution: string;
        id?: string | null;
      }[]
    | null;
  becomeHeading?: string | null;
  /**
   * Short paragraph below the heading
   */
  becomeBody?: string | null;
  becomeBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  becomeCtaLabel?: string | null;
  becomeCtaHref?: string | null;
  becomeSecondaryCtaLabel?: string | null;
  becomeSecondaryCtaHref?: string | null;
  /**
   * Named partnership lead shown on the right meta panel, e.g. "Amal — Director of Growth". Leave blank to hide.
   */
  partnershipLead?: string | null;
  /**
   * Partnership-specific inbox (defaults to partners@himayat.com.au). Used for both the meta panel row and the mailto: when the primary CTA is left as default.
   */
  partnerEmail?: string | null;
  /**
   * Public link to the partnership deck PDF. When set, the secondary CTA becomes "Download partnership deck (PDF)" and points here.
   */
  deckUrl?: string | null;
  /**
   * Optional link to a partner-requirements / criteria page. Shown as a "View partner requirements →" row on the meta panel when set.
   */
  requirementsUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  supportEmail?: T;
  phone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        isExternal?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-bar_select".
 */
export interface AnnouncementBarSelect<T extends boolean = true> {
  enabled?: T;
  message?: T;
  linkText?: T;
  linkHref?: T;
  bgColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signup-page-content_select".
 */
export interface SignupPageContentSelect<T extends boolean = true> {
  foundations?:
    | T
    | {
        title?: T;
        tagline?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        addon?: T;
        trustItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  growth?:
    | T
    | {
        title?: T;
        tagline?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        addon?: T;
        trustItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  accelerate?:
    | T
    | {
        title?: T;
        tagline?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        addon?: T;
        trustItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-page_select".
 */
export interface PartnersPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeading?: T;
  heroSubheading?: T;
  heroCtaLabel?: T;
  heroCtaHref?: T;
  heroSecondaryCtaLabel?: T;
  heroSecondaryCtaHref?: T;
  heroChips?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featuredWallHeading?: T;
  featuredWallLead?: T;
  directoryHeading?: T;
  directoryLead?: T;
  benefitsHeading?: T;
  benefitsLead?: T;
  benefits?:
    | T
    | {
        tag?: T;
        heading?: T;
        body?: T;
        handnote?: T;
        id?: T;
      };
  proofHeading?: T;
  proofLead?: T;
  proofStats?:
    | T
    | {
        tag?: T;
        num?: T;
        unit?: T;
        heading?: T;
        body?: T;
        id?: T;
      };
  proofQuotes?:
    | T
    | {
        text?: T;
        attribution?: T;
        id?: T;
      };
  becomeHeading?: T;
  becomeBody?: T;
  becomeBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  becomeCtaLabel?: T;
  becomeCtaHref?: T;
  becomeSecondaryCtaLabel?: T;
  becomeSecondaryCtaHref?: T;
  partnershipLead?: T;
  partnerEmail?: T;
  deckUrl?: T;
  requirementsUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}